name: Corkiejp's Social World
theme: minima
descriptio: I'm not a developer, and this site is an experimental github pages!
url: "https://corkiejp.github.io"
baseurl: "/corkiejp.html"
google_site_verification: "4f3gqLpbut6EtRQ00QZ74jXEKf1nDrFM5G3sq2tFKyQ"
